# Generated by Django 3.2.7 on 2021-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_auto_20210926_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
