# Generated by Django 3.2.7 on 2021-12-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_user_is_password_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_password_reset',
            new_name='password_reset_requested',
        ),
    ]
