# Generated by Django 3.2.7 on 2022-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_rename_is_password_reset_user_password_reset_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
